server.port=${PORT:8080}

# Application Name
spring.application.name=quickpay-backend

# Explicit Database Name
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:quickpay_db}

# Connects to MongoDB. Uses MONGO_URI environment variable if set, otherwise defaults to local MongoDB.
spring.mongodb.uri=${MONGO_URI}

# Auto-create collection indexes defined in @Document models
spring.data.mongodb.auto-index-creation=true