server.port=8080

# Application Name
spring.application.name=fakepay-backend

# Explicit Database Name
spring.data.mongodb.database=fakepay_db

# Connects to 'fakepay_db'. Creates it if it doesn't exist; reuses it if it does.
spring.mongodb.uri=mongodb://localhost:27017/fakepay_db

# Auto-create collection indexes defined in @Document models
spring.data.mongodb.auto-index-creation=true